name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: heroku/actions/cli@v1
        with:
          cli_auth_token: ${{ secrets.HEROKU_API_KEY }}
          app_name: my-api
          args: |
            heroku git:remote -a my-api
            git push heroku HEAD:main
